"use client";

import { useState } from "react";
import { Badge } from "@astryxdesign/core/Badge";
import { Button } from "@astryxdesign/core/Button";
import { Card } from "@astryxdesign/core/Card";
import { Heading } from "@astryxdesign/core/Heading";
import { ProgressBar } from "@astryxdesign/core/ProgressBar";
import { Selector } from "@astryxdesign/core/Selector";
import { Text } from "@astryxdesign/core/Text";
import { TextArea } from "@astryxdesign/core/TextArea";
import { contractorById, money, projectById } from "../lib/demo";
import { useDemo } from "./providers";
import { PageIntro, StatusBadge, MilestoneRow, Metric } from "./components";

export function ProfileRoute({ id }: { id: string }) {
  const c = contractorById(id); const { state } = useDemo();
  return <section className="page"><div className="shell"><Button label="Back to discover" variant="ghost" href="/" /><div className="profile-hero"><div><Text className="eyebrow" type="supporting" weight="bold">{c.area} · {c.specialty}</Text><Heading level={1} type="display-2">{c.name}</Heading><Text color="secondary" display="block">{c.summary}</Text><Text className="verified-line" color="accent" weight="bold" display="block">✓ {c.verified ? "Identity and business evidence reviewed" : "Profile in review"}</Text><div className="profile-stats"><Metric value={c.rating.toString()} label={`Rating from ${c.reviews} reviews`} /><Metric value={c.projects.toString()} label="Completed projects" /><Metric value={c.response} label="Typical response" /></div><Card className="surface-card"><Heading level={2}>How this studio works</Heading><div className="pill-row">{c.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div><Text color="secondary" display="block">Expect a structured brief, weekly evidence updates and a handover pack you can keep. This prototype shows the trust layer around that relationship.</Text></Card></div><Card className="profile-aside" variant="blue"><Badge label={c.verified ? "Verified studio" : "Profile in review"} variant={c.verified ? "success" : "warning"} /><Heading level={3}>Ready to make the brief clear?</Heading><Text color="secondary" display="block">Request a quote with budget, timeline and what good looks like.</Text><Button label="Request a quote" variant="primary" href={`/quotes/${c.id}`} width="100%" /><Button label="View shortlist" variant="secondary" href="/shortlist" width="100%" /></Card></div><div className="section-heading"><div><Heading level={2}>Proof, not promises</Heading><Text color="secondary" display="block">Reviews unlock when a project reaches completion.</Text></div></div><Card className="surface-card"><div className="activity-list"><div className="activity-item"><div><Text weight="bold" display="block">Paid project evidence</Text><Text type="supporting" color="secondary">Milestone receipts and handover files are attached to the project record.</Text></div><StatusBadge label="Available" variant="success" /></div><div className="activity-item"><div><Text weight="bold" display="block">Client review history</Text><Text type="supporting" color="secondary">{c.reviews} reviews from completed work.</Text></div><StatusBadge label={c.verified ? "Verified" : "Pending"} variant={c.verified ? "success" : "warning"} /></div></div></Card></div></section>;
}

export function QuoteRoute({ contractorId }: { contractorId: string }) {
  const c = contractorById(contractorId); const { dispatch } = useDemo(); const [brief, setBrief] = useState("A warm, practical refresh for a 1,200 sq ft terrace home."); const [budget, setBudget] = useState("RM80k–RM120k"); const [timeline, setTimeline] = useState("Start in 6–8 weeks"); const [sent, setSent] = useState(false);
  return <section className="page"><div className="shell"><div className="form-card"><Button label="Back to profile" variant="ghost" href={`/contractors/${c.id}`} /><PageIntro eyebrow="Quote request" title={`Start a clear conversation with ${c.name}.`} copy="The best requests are specific enough to price, but open enough to collaborate on." /><div className="stepper"><div className="step active">1 · Brief</div><div className="step">2 · Quote</div><div className="step">3 · Project</div></div><Card className="surface-card"><div className="form-grid"><TextArea label="What are you hoping to change?" value={brief} onChange={setBrief} rows={5} /><div className="form-grid form-grid-two"><Selector label="Working budget" options={["RM50k–RM80k", "RM80k–RM120k", "RM120k–RM200k", "RM200k+"]} value={budget} onChange={setBudget} /><Selector label="Timing" options={["Start in 2–4 weeks", "Start in 6–8 weeks", "Exploring for now"]} value={timeline} onChange={setTimeline} /></div></div><div className="form-actions"><span className="tag">No payment required to send</span><Button label={sent ? "Request sent" : "Send quote request"} variant="primary" isDisabled={sent} onClick={() => { dispatch({ type: "create_request", contractorId: c.id, brief, budget, timeline }); setSent(true); }} /></div></Card>{sent && <Card className="toast-card" variant="green"><Text weight="bold">Quote request sent.</Text><Text color="secondary">The next step is a structured quote.</Text></Card>}</div></div></section>;
}

export function ProjectRoute({ id }: { id: string }) {
  const { state, dispatch } = useDemo(); const project = projectById(state, id); const c = contractorById(project.contractorId); const approved = project.milestones.filter((m) => m.status === "approved" || m.status === "refunded").length; const progress = Math.round((approved / project.milestones.length) * 100);
  return <section className="page"><div className="shell"><PageIntro eyebrow="Homeowner workspace" title={project.name} copy={`Project ${project.id} · ${c.name} · ${project.status}`} action={<Button label="View studio" variant="secondary" href={`/contractors/${c.id}`} />} /><div className="dashboard-grid"><Card><Text type="large" weight="bold" display="block">{money(project.total)}</Text><Text type="supporting" color="secondary">Project value</Text></Card><Card><Text type="large" weight="bold" display="block">{approved}/{project.milestones.length}</Text><Text type="supporting" color="secondary">Milestones released</Text></Card><Card><Text type="large" weight="bold" display="block">{project.status === "complete" ? "Complete" : "Active"}</Text><Text type="supporting" color="secondary">Current status</Text></Card><Card><Text type="large" weight="bold" display="block">Held</Text><Text type="supporting" color="secondary">Next release state</Text></Card></div><div className="two-col"><Card className="surface-card"><Heading level={2}>Milestone ledger</Heading><Text color="secondary" display="block">Release only when the evidence matches the agreed stage.</Text><ProgressBar label="Project progress" value={progress} hasValueLabel variant="success" /><div className="timeline">{project.milestones.map((m) => <MilestoneRow key={m.id} project={project} milestone={m} />)}</div>{project.status === "planning" && <Button label="Fund first milestone (simulation)" variant="primary" onClick={() => dispatch({ type: "fund_project", projectId: project.id })} />} {project.status !== "complete" && project.milestones.every((m) => m.status === "approved" || m.status === "refunded") && <Button label="Mark project complete" variant="primary" onClick={() => dispatch({ type: "complete_project", projectId: project.id })} />}</Card><aside className="stack"><Card><Heading level={3}>Payment guardrails</Heading><Text color="secondary" display="block">Trustible shows the sequence here; it does not custody funds in this prototype.</Text><StatusBadge label="Simulation only" variant="warning" /></Card><Card><Heading level={3}>Receipts & records</Heading><Text color="secondary" display="block">Every action is recorded in this demo so the homeowner and contractor share one timeline.</Text><Button label="Open contractor view" variant="secondary" href={`/contractor/projects/${project.id}`} /></Card>{project.reviewUnlocked && <Card><Heading level={3}>Review unlocked</Heading><Text color="secondary" display="block">Your completed project can now become proof for the next homeowner.</Text><Button label="Write a verified review" variant="primary" /></Card>}</aside></div></div></section>;
}

export function ContractorProjectRoute({ id }: { id: string }) { const { state } = useDemo(); const project = projectById(state, id); const c = contractorById(project.contractorId); return <section className="page"><div className="shell"><PageIntro eyebrow="Contractor workspace" title={project.name} copy={`Client-side view · ${project.id}`} action={<Button label="Back to dashboard" variant="secondary" href="/contractor/dashboard" />} /><div className="two-col"><Card className="surface-card"><Heading level={2}>Submit evidence by milestone</Heading><Text color="secondary" display="block">Keep updates attached to the stage they support. The homeowner sees the same ledger.</Text><div className="timeline">{project.milestones.map((m) => <MilestoneRow key={m.id} project={project} milestone={m} role="contractor" />)}</div></Card><aside className="stack"><Card><Heading level={3}>Client</Heading><Text color="secondary" display="block">Homeowner workspace is active. Releases happen only after approval.</Text><StatusBadge label="Shared timeline" variant="info" /></Card><Card><Heading level={3}>Studio</Heading><Text color="secondary" display="block">{c.name} · {c.area}</Text><Button label="View public profile" variant="secondary" href={`/contractors/${c.id}`} /></Card></aside></div></div></section>; }

export function OnboardingRoute() { const [done, setDone] = useState(false); return <section className="page"><div className="shell"><div className="form-card"><PageIntro eyebrow="For professionals" title="Make your proof legible." copy="Onboarding is a guided checklist in this prototype. Real verification would require partner and regulatory review." /><Card className="surface-card"><div className="activity-list"><div className="activity-item"><div><Text weight="bold" display="block">1 · Identity</Text><Text type="supporting" color="secondary">Owner identity and contact details</Text></div><StatusBadge label="Ready" variant="success" /></div><div className="activity-item"><div><Text weight="bold" display="block">2 · Business evidence</Text><Text type="supporting" color="secondary">SSM/CIDB registration evidence placeholder</Text></div><StatusBadge label="Upload later" variant="warning" /></div><div className="activity-item"><div><Text weight="bold" display="block">3 · Portfolio proof</Text><Text type="supporting" color="secondary">Connect social or upload completed project records</Text></div><StatusBadge label="Upload later" variant="warning" /></div></div><div className="form-actions"><span className="tag">Demo onboarding · no documents uploaded</span><Button label={done ? "Profile checklist complete" : "Complete demo checklist"} variant="primary" onClick={() => setDone(true)} /></div></Card></div></div></section>; }

export function DashboardRoute() { const { state } = useDemo(); const active = state.projects.filter((p) => p.status !== "complete").length; return <section className="page"><div className="shell"><PageIntro eyebrow="Contractor dashboard" title="Keep every promise in one place." copy="A dual-sided view for leads, active work and proof requests." action={<Button label="Complete onboarding" variant="primary" href="/contractor/onboarding" />} /><div className="dashboard-grid"><Card><Text type="large" weight="bold" display="block">{active}</Text><Text type="supporting" color="secondary">Active projects</Text></Card><Card><Text type="large" weight="bold" display="block">{state.requests.length}</Text><Text type="supporting" color="secondary">Quote requests</Text></Card><Card><Text type="large" weight="bold" display="block">RM68.6k</Text><Text type="supporting" color="secondary">Awaiting release</Text></Card><Card><Text type="large" weight="bold" display="block">4.9</Text><Text type="supporting" color="secondary">Verified rating</Text></Card></div><div className="two-col"><Card className="surface-card"><Heading level={2}>Current work</Heading><div className="activity-list">{state.projects.map((project) => <div className="activity-item" key={project.id}><div><Text weight="bold" display="block">{project.name}</Text><Text type="supporting" color="secondary">{project.id} · {project.status}</Text></div><Button label="Open" variant="secondary" href={`/contractor/projects/${project.id}`} /></div>)}</div></Card><aside className="stack"><Card><Heading level={3}>Your public proof</Heading><Text color="secondary" display="block">Verified profiles connect completed projects, evidence and client reviews.</Text><Button label="Preview profile" variant="secondary" href="/contractors/nook" /></Card><Card><Heading level={3}>Next best action</Heading><Text color="secondary" display="block">Submit evidence for the active build milestone to keep the client moving.</Text><Button label="Submit an update" variant="primary" href="/contractor/projects/TRU-DEMO-2183" /></Card></aside></div></div></section>; }

