/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: app\trustible-theme.ts
 * Command: astryx theme build app\trustible-theme.ts --out app\trustible-theme.css
 * CLI: @astryxdesign/cli@0.4.3
 * Core: @astryxdesign/core@0.4.3
 */

/// <reference path="./trustible.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const trustibleTheme: DefinedTheme;
